version: "3.9"
services:
  astrology-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - astrology-mongodb
    ports:
      - "4001:4000"
    volumes:
      - ./:/usr/src/app
    restart: always

  astrology-mongodb:
    image: "mongo:6.0"
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data: